### PR TITLE
Readme

### PR DESCRIPTION
**Pull request by themrcesi**
Final version of the Readme.

### CODE REVIEW

**Comment by themrcesi** [comment]
Not ready to merge, sections docker and load tests in progress.

**Comment by InigoGutierrez** [comment]
I fixed some issues marked by Codecov and a couple typos. Maybe saying that we are concerned about every kind of user is a bit of using empty words, and we could have problems if someone asks for support we really aren't prepared for, but stating that we support colorblind people is really nice.

**Comment by InigoGutierrez** [comment]
Codacy asks to remove indentation when it is added and to add it when it is removed, so 9 more warnings for technical debt I guess.

**Review by lamasumas — APPROVED** [review]
LGTM

**Pull request merged**
