### PR TITLE
Solved issue #48

### LINKED ISSUE #48: [FEATURE REQUEST] Restricted file extensions when uploading files
In the upload route component, we are allowing to upload any file when we actully want to upload images or videos.

**Describe the solution you'd like**
We should only allow uploads of files with the correct extensions.

**Describe alternatives you've considered**
I found this component, that seem to be easy to implement and allow us to set the allowed extensions: '@progress/kendo-react-upload'

### PR DESCRIPTION
**Pull request by alvarogarinf**
When uploading a route know you can:
- Select only .gpx and .kml  file types in the route file
- Select only images file types in the image form
- Select only video file types in the video form

Closes #48

### CODE REVIEW

**Comment by themrcesi** [comment]
Nice!

**Comment by themrcesi** [comment]
@alvarogarinf you kept working on your branch, while marcos updated a litle bit UPloadRoute.js so as to improve the style and those changes are already in dev branch.

As you can see now, there are some conflicts because of that. Marcos used an UploadButton component to upload the files. Can you adapt your changes to Marcos implementation? 

(If you prefer you can create a new branch from dev, it´s already up to date)

**Comment by alvarogarinf** [comment]
Ok, i will modify it and re-upload it

**Comment by themrcesi** [comment]
I think the easiest option would be to create a new branch from dev, becasue this branch has a lot of warnings that have already been solved in dev branch :) (less work to do)

**Comment by themrcesi** [comment]
> Ok, i will modify it and re-upload it

@alvarogarinf I was checking whether it exists a propierty accept (the one that you used in "input") for Form.Control (the react-bootstrap component used by Marcos), but I haven´t found it.

**Comment by alvarezGarciaMarcos** [comment]
Maybe the best thing here is to leave the selection of the files as it is for this deliverable. The project is working now, so I think that this feature could be implemented for the next deliverable.

**Comment by alvarogarinf** [comment]
You are right, we leave it for the next deriverable

**Pull request closed without merging**
