### PR TITLE
Storing info tested

### PR DESCRIPTION
**Pull request by InigoGutierrez**
Functionallity is done and tests should be passing; maybe sharing fails when creating the notification on the remote pod, since permissions are difficult to test locally. We can merge to see how it works.

### CODE REVIEW

**Comment by themrcesi** [comment]
A W E S O M E

**Comment by InigoGutierrez** [comment]
Interesting! Now this branch's version is compiling fine, but the pull request version, which I guess is testing the proyect after the merge with dev, is not. I guess this is because the error comes from the interaction between this and other branches.

To check this, test the merge locally, probably best by creating a test from `dev` and merging `storingInfo` into it:

```
git checkout dev
git checkout -b devMergeTest
git merge storingInfo
```

In this state, `npm run build` should fail, but it does not fail neither in `dev` nor `storingInfo`. The differences between `storingInfo` and the resulting merge, which seemingly are where the error has its source, can be checked with `git diff storingInfo devMergeTest`, but I have not seen anything special here. Maybe other person can add insight into this fail.

**Comment by InigoGutierrez** [comment]
Also regarding this merge: the usage of `shareRouteToPod()` from `solid/routes.js` should be updated in `store/reducers/RouteReducer.js`, line ~70, which is the only place where it seems to be used, to comply with the new arguments it needs. I don't think this has to deal with the Travis fail, since this has been in this state for many commits.

**Comment by themrcesi** [comment]
We can´t use solid-acl-utils by the moment because we are getting an error when travis tries to build the app.

**Comment by InigoGutierrez** [comment]
We just need to use the module which creates the .acl files to also update them, although I didn't found how to when I looked at it. I guess if the create file overrides the existing file we just need to first get it, read its permissions, expand them and upload in each function which adds permissions.

**Comment by themrcesi** [comment]
Now tests don´t pass locally, think beacuse of the integration of the shared routes while reading routes.

**Comment by themrcesi** [comment]
> Also regarding this merge: the usage of `shareRouteToPod()` from `solid/routes.js` should be updated in `store/reducers/RouteReducer.js`, line ~70, which is the only place where it seems to be used, to comply with the new arguments it needs. I don't think this has to deal with the Travis fail, since this has been in this state for many commits.

Already corrected this part. Permissions still fail.

**Comment by InigoGutierrez** [comment]
> > Also regarding this merge: the usage of `shareRouteToPod()` from `solid/routes.js` should be updated in `store/reducers/RouteReducer.js`, line ~70, which is the only place where it seems to be used, to comply with the new arguments it needs. I don't think this has to deal with the Travis fail, since this has been in this state for many commits.
> 
> Already corrected this part. Permissions still fail.

Yes, for some reason I still don't know the `createACL` method is failing so I just catched and logged the error for the moment.

**Comment by themrcesi** [comment]
Suggest starting a new branch from dev: dealing with acl files and share routes, comments, etc...

**Comment by InigoGutierrez** [comment]
This functionality is now in a different route, so this merge is not needed.

**Pull request closed without merging**
