### PR TITLE
Runtime view

### LINKED ISSUE #21: Create sequence diagrams

### PR DESCRIPTION
**Pull request by themrcesi**
Activity diagramas added: upload a route, share a route.

Closes #21

### CODE REVIEW

**Comment by themrcesi** [comment]
As you can see, they are just very simple activity diagrams to show these two actions. 

Our idea should be to replaced them with proper sequence diagrams once we know the actual behaviour of our application.

**Comment by themrcesi** [comment]
In order to view the view the diagrams, you need to checkout my branch, pull it and then npm run docs :)

**Review by alvarogarinf — APPROVED** [review]

**Comment by lamasumas** [comment]
LGTM

**Review by lamasumas — APPROVED** [review]
LGTM

**Pull request merged**
