### PR TITLE
Documentation 0.1

### PR DESCRIPTION
**Pull request by alvarogarinf**
I have add:
4.1: Introduction
4.2: Decisions

### CODE REVIEW

**Comment by themrcesi** [comment]
What's TBD? Did you want to mean TDD? (test driven development)

**Comment by alvarogarinf** [comment]
No. I was refering t TBD to be determinated

**Comment by themrcesi** [comment]
Remember to add any weird word to the glossary 💪🏿

**Comment by lamasumas** [comment]
Fix NodeJS, we dont use node for the server -side we used it for modules management (instalation and deployment). And table 2 should be merge with table1

**Pull request merged**
