### PR TITLE
Main menu

### PR DESCRIPTION
**Pull request by garciaAlvarezPelayo**

### CODE REVIEW

**Comment by themrcesi** [comment]
@garciaAlvarezPelayo please review your code, there is one warning that is making your code fail.

**Comment by themrcesi** [comment]
> @garciaAlvarezPelayo please review your code, there is one warning that is making your code fail.

Already fixed.

**Comment by alvarezGarciaMarcos** [comment]
Regarding styling, I can work on it tomorrow, but don't close the PR so I can work on it before merging.

**Comment by alvarezGarciaMarcos** [comment]
I added the styling for the first derivable of this part. I'm concious that it is not the finish I would like to give to it, but in the following derivables we have to check it and make some adjustments.

**Review by themrcesi — APPROVED** [review]

**Pull request merged**
