### PR TITLE
Storing info

### LINKED ISSUE #29: Integrate SOLID with React
Start the integration of Solid in the prototype that we have.

### PR DESCRIPTION
**Pull request by InigoGutierrez**
Added two basic operations to store a route and to retrieve all routes to solid/routes.js, just to show how this could be achieved using solid-file-client. A temporal text field is added to the upload route view so route points can be specified somewhere, until we get file actual processing. Work on this branch or on branches derived from it can continue, but I think it is important to get a common base to make all other operations over.

Resolves #29.

### CODE REVIEW

**Comment by themrcesi** [comment]
Maybe delete the functionality of writing points? I check the other part now, we must resolve conflicts.

**Comment by themrcesi** [comment]
@InigoGutierrez do you know what app source should I add to my POD in order to work?? I´ve tried with localhost but it doesn´t work.

**Comment by themrcesi** [comment]
And nice job! :)

**Comment by InigoGutierrez** [comment]
The needed url is `http://localhost:3000` (without a dash at the end).

**Comment by themrcesi** [comment]
> The needed url is `http://localhost:3000` (without a dash at the end).

Thanks!

**Review by themrcesi — APPROVED** [review]
Ready to merge.

**Pull request merged**
