### PR TITLE
Added missing words to locale

### PR DESCRIPTION
**Pull request by lamasumas**

### CODE REVIEW

**Comment by themrcesi** [comment]
Don´t merge yet, I´ll do tests of them :) in this branch

**Comment by themrcesi** [comment]
Notifications tests done, check them please @lamasumas and merge whenever you want.

**Review by themrcesi — COMMENTED** [review]
Notifications tests done, check them please @lamasumas and merge whenever you want.

**Review by InigoGutierrez — APPROVED** [review]
By reviewing files changed here in the pull request page of GitHub it says `routes.js` and `routes.test.js` would be affected, I guess because of some confusion from GitHub by this branch being created from `solid_modifications_testing`, but I faked the merge locally and only 9 files would be affected:
```
src/components/layout/navbar/NavBar.js
src/components/layout/navbar/tests/NavBar.test.js
src/components/layout/notifications/Notifications.js
src/components/layout/notifications/notification/Notification.js
src/components/layout/notifications/notification/test/Notification.test.js
src/components/layout/notifications/notificationsList/NotificationsList.js
src/components/layout/notifications/notificationsList/test/NotificationsList.test.js
src/components/layout/notifications/test/Notifications.test.js
src/utils/locales.js
```
so I assume it is safe to merge and only those 9 will be affected. Good job!

**Comment by InigoGutierrez** [comment]
Note that there is a warning coming from `NavBar.test.js` about the need for list items to have unique ids.

**Pull request merged**
