### PR TITLE
Comment routes model

### PR DESCRIPTION
**Pull request by lamasumas**
A prototype for the comments done, it remains the functional (solid stuff) part

### CODE REVIEW

**Comment by themrcesi** [comment]
It doesn't build, maybe some warnings? @lamasumas Tomorrow I check it.

**Comment by lamasumas** [comment]
> It doesn't build, maybe some warnings? @lamasumas Tomorrow I check it.

Problems solved, now it can be built without any problem

**Review by themrcesi — APPROVED** [review]

**Comment by alvarezGarciaMarcos** [comment]
I can finish adding the comments functionality and close this pull request with my changes.

**Comment by themrcesi** [comment]
Ready to merge? @lamasumas @alvarezGarciaMarcos

**Comment by alvarezGarciaMarcos** [comment]
The only part that is left is server side, comments right now are in the state.

**Comment by themrcesi** [comment]
> The only part that is left is server side, comments right now are in the state.

Okay, so lets wait for @InigoGutierrez ´s part.

**Comment by lamasumas** [comment]
> Ready to merge? @lamasumas @alvarezGarciaMarcos

I think for my part is done

**Pull request merged**
