### PR TITLE
Documentation section 6 improved

### PR DESCRIPTION
**Pull request by lamasumas**

### CODE REVIEW

**Comment by InigoGutierrez** [comment]
Correct me if I am wrong, but shouldn't we also add the routes view? Also, I think the action of displaying the route in the friend's app should not be part of the diagram since it is not something the instance of the application does. I could change it if you are ok with it.

**Review by InigoGutierrez — APPROVED** [review]
I made the change, so let's update this.

**Comment by themrcesi** [comment]
Sequence diagrams done, please check them.

**Comment by InigoGutierrez** [comment]
Just one comment. The middleware loads the routes asynchronously, right, but doesn't it have to wait untit it finishes so the right state can be passed to the store?

**Comment by alvarezGarciaMarcos** [comment]
The middleware works under the hood to load the route into the state, but the application does not hang until the routes are loaded. Everything still works fine, and when the routes are loaded, they are displayed on the interface.

**Comment by themrcesi** [comment]
> Just one comment. The middleware loads the routes asynchronously, right, but doesn't it have to wait untit it finishes so the right state can be passed to the store?

It keeps working, and then when it dispatches the loadRoutes/Email/FriendsSuccess action, there it´s where the state is updated with the requested data.

Just enable the console, and we can see there that firstly the loadRouteRequest is processed (wecan see the change in the state:loading) and finally the loadRoutesSuccess.

**Review by themrcesi — APPROVED** [review]

**Comment by InigoGutierrez** [comment]
> The middleware works under the hood to load the route into the state, but the application does not hang until the routes are loaded. Everything still works fine, and when the routes are loaded, they are displayed on the interface.

> It keeps working, and then when it dispatches the loadRoutes/Email/FriendsSuccess action, there it´s where the state is updated with the requested data.

I was really commenting on the point 4 of the explanation of 6.2.1 (Loading routes from POD), which says that the reducer gives a response at the same time the routes are loaded by the middleware; it should probably be changed so it says that the response is given after the routes are loaded. Sorry, just wanted to point to that specific wording, I should have been more clear.

**Comment by themrcesi** [comment]
Ready to merge?

**Review by alvarezGarciaMarcos — APPROVED** [review]

**Pull request merged**
