### PR TITLE
Required fields to upload a route: name & file

### PR DESCRIPTION
**Pull request by alvarogarinf**
I have added the functionality to not let the user push the submit button until the name has been written and the file has been uploaded

### CODE REVIEW

**Review by themrcesi — APPROVED** [review]
It perfectly works!

**Comment by themrcesi** [comment]
We need also to allow only .gpx files!!!

**Comment by alvarogarinf** [comment]
I will add those changes to this PR

**Comment by alvarogarinf** [comment]
I have added the requested changes @themrcesi

**Pull request merged**
